services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend_django.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend_django.settings
      - key: PYTHON_VERSION
        value: 3.10
