# Generated by Django 5.1.7 on 2025-03-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='route',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus_tracking.user'),
        ),
    ]
